apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tkj3b3uzz-nodejs 
  janus-idp.io/tekton: tkj3b3uzz-nodejs
  backstage.io/kubernetes-id: tkj3b3uzz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tkj3b3uzz-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  