apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tkj3b3uzz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tkj3b3uzz-nodejs 
  name: tkj3b3uzz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tkj3b3uzz-nodejs 
